/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.classes;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import persistencia.Usuarios;
import persistencia.UsuariosDAO;

/**
 *
 * @author JONATASWILLIAMSILVES
 */
public class FrmCadUser extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadCli
     */
    private List<Usuarios> users;

    public FrmCadUser() throws SQLException {
        initComponents();
        criarListaUsers();
        preencheCampos();
    }

    private void preencheCampos() {
        int index = Integer.parseInt(cmbCod.getItemAt(cmbCod.getSelectedIndex()));
        for (Usuarios user : this.users) {
            if (user.getCodigo() == index) {
                txtNome.setText(user.getNome());
            }
        }
    }

    private void criarListaUsers() throws SQLException {
        cmbCod.removeAllItems();
        UsuariosDAO userdb = new UsuariosDAO();
        this.users = userdb.findAll();
        for (Usuarios user : this.users) {
            cmbCod.addItem(Integer.toString(user.getCodigo()));
        }
        cmbCod.addItem("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCad = new javax.swing.JButton();
        btnCanc = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pwdSenha2 = new javax.swing.JPasswordField();
        pwdSenha = new javax.swing.JPasswordField();
        btnVoltar = new javax.swing.JButton();
        btnProx = new javax.swing.JButton();
        cmbCod = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");

        jLabel1.setText("Nome");

        jLabel2.setText("Senha");

        btnCad.setText("Cadastrar");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });

        btnCanc.setText("Cancelar");
        btnCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancActionPerformed(evt);
            }
        });

        txtNome.setEditable(false);

        jLabel3.setText("Confirme a Senha");

        pwdSenha2.setEditable(false);

        pwdSenha.setEditable(false);

        btnVoltar.setText("<");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnProx.setText(">");
        btnProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxActionPerformed(evt);
            }
        });

        jLabel4.setText("Código");

        btnEditar.setText("Editar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVoltar)
                                .addGap(27, 27, 27)
                                .addComponent(cmbCod, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProx))
                            .addComponent(pwdSenha2)
                            .addComponent(pwdSenha)
                            .addComponent(txtNome)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCad)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCanc, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnProx)
                    .addComponent(cmbCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pwdSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCad)
                    .addComponent(btnCanc)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente cancelar o cadastro?", "Cancelar", JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancActionPerformed

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        // TODO add your handling code here:
        String nome, senha, senha2;
        nome = txtNome.getText();
        senha = pwdSenha.getText();
        senha2 = pwdSenha2.getText();

        if (nome.isEmpty() || senha.isEmpty() || senha2.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Algum campo está em branco");
        } else if (!senha.equals(senha2)) {
            JOptionPane.showMessageDialog(rootPane, "Senhas não conferem!");
        } else {

            UsuariosDAO userdb = new UsuariosDAO();
            try {
                userdb.insert(nome, senha);
            } catch (SQLException ex) {
                Logger.getLogger(FrmCadUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane, "Usuário cadastrado com sucesso!");
            txtNome.setText("");
            pwdSenha.setText("");
            pwdSenha2.setText("");
            cmbCod.setEditable(true);
            txtNome.setEditable(false);
            pwdSenha.setEditable(false);
            pwdSenha2.setEditable(false);
            try {
                criarListaUsers();
            } catch (SQLException ex) {
                Logger.getLogger(FrmCadUser.class.getName()).log(Level.SEVERE, null, ex);
            }
            preencheCampos();

        }

    }//GEN-LAST:event_btnCadActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        if (cmbCod.getSelectedIndex() == (cmbCod.getItemCount() - cmbCod.getItemCount())) {

        } else {
            if (Integer.parseInt(cmbCod.getItemAt(cmbCod.getSelectedIndex() +1)) == 0) {
                cmbCod.setVisible(true);
                txtNome.setEditable(false);
                pwdSenha.setEditable(false);
                pwdSenha2.setEditable(false);
                //cmbCod.setSelectedIndex(cmbCod.getSelectedIndex() + 1);
            }
            cmbCod.setSelectedIndex(cmbCod.getSelectedIndex() - 1);
            preencheCampos();
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(cmbCod.getItemAt(cmbCod.getSelectedIndex()+1)) == 0) {
            cmbCod.setVisible(false);
            txtNome.setEditable(true);
            txtNome.setText("");
            pwdSenha.setEditable(true);
            pwdSenha2.setEditable(true);

        } else {
            cmbCod.setSelectedIndex(cmbCod.getSelectedIndex() + 1);
            preencheCampos();
        }
    }//GEN-LAST:event_btnProxActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnCanc;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnProx;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbCod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JPasswordField pwdSenha2;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
