/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.classes;

import java.text.SimpleDateFormat;
import java.time.Instant;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.util.TimerTask;
import java.util.Timer;

/**
 *
 * @author potato
 */
public class FrmMenu extends javax.swing.JFrame {

	/**
	 * Creates new form frmMenu
	 */
    
        Calendar calendario = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        Date hora;
        Timer tempo;
        
	public FrmMenu() {
		initComponents();
                lblData.setText(Integer.toString(calendario.get(Calendar.YEAR)) + "-" + Integer.toString(calendario.get(Calendar.MONTH)+1) + "-" + Integer.toString(calendario.get(Calendar.DAY_OF_MONTH)));
                tempo = new Timer();
                tempo.schedule(new Hora(), 0, 1000);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jSeparator1 = new javax.swing.JSeparator();
                jToolBar1 = new javax.swing.JToolBar();
                btnUsers = new javax.swing.JButton();
                btnDisco = new javax.swing.JButton();
                btnPrinter = new javax.swing.JButton();
                btnDinheiro = new javax.swing.JButton();
                btnAnexo = new javax.swing.JButton();
                btnCancelar = new javax.swing.JButton();
                lblData = new javax.swing.JLabel();
                lblHora = new javax.swing.JLabel();
                jMenuBar1 = new javax.swing.JMenuBar();
                jMenu1 = new javax.swing.JMenu();
                jMenuItem1 = new javax.swing.JMenuItem();
                jMenuItem2 = new javax.swing.JMenuItem();
                jMenuItem3 = new javax.swing.JMenuItem();
                menuSair = new javax.swing.JMenuItem();
                jMenu2 = new javax.swing.JMenu();
                jMenuItem5 = new javax.swing.JMenuItem();
                jMenuItem6 = new javax.swing.JMenuItem();
                jMenu3 = new javax.swing.JMenu();
                jMenuItem7 = new javax.swing.JMenuItem();
                jMenu4 = new javax.swing.JMenu();
                jMenuItem8 = new javax.swing.JMenuItem();
                jMenuItem9 = new javax.swing.JMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Turismo - Menu");
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                jToolBar1.setFloatable(false);
                jToolBar1.setRollover(true);

                btnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios.png"))); // NOI18N
                btnUsers.setFocusable(false);
                btnUsers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnUsers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jToolBar1.add(btnUsers);

                btnDisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/hd.png"))); // NOI18N
                btnDisco.setFocusable(false);
                btnDisco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnDisco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jToolBar1.add(btnDisco);

                btnPrinter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/impressora.png"))); // NOI18N
                btnPrinter.setFocusable(false);
                btnPrinter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnPrinter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jToolBar1.add(btnPrinter);

                btnDinheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dinheiro.png"))); // NOI18N
                btnDinheiro.setFocusable(false);
                btnDinheiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnDinheiro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jToolBar1.add(btnDinheiro);

                btnAnexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anexo.png"))); // NOI18N
                btnAnexo.setFocusable(false);
                btnAnexo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnAnexo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jToolBar1.add(btnAnexo);

                btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
                btnCancelar.setFocusable(false);
                btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jToolBar1.add(btnCancelar);

                lblData.setText("jLabel1");

                lblHora.setText("jLabel2");

                jMenu1.setText("Cadastro");

                jMenuItem1.setText("Clientes");
                jMenu1.add(jMenuItem1);

                jMenuItem2.setText("Viagens");
                jMenu1.add(jMenuItem2);

                jMenuItem3.setText("Usuários");
                jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItem3ActionPerformed(evt);
                        }
                });
                jMenu1.add(jMenuItem3);

                menuSair.setText("Sair");
                menuSair.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                menuSairActionPerformed(evt);
                        }
                });
                jMenu1.add(menuSair);

                jMenuBar1.add(jMenu1);

                jMenu2.setText("Consultas");

                jMenuItem5.setText("Nome Clientes");
                jMenu2.add(jMenuItem5);

                jMenuItem6.setText("Código Viagem");
                jMenu2.add(jMenuItem6);

                jMenuBar1.add(jMenu2);

                jMenu3.setText("Vendas");

                jMenuItem7.setText("Vendas");
                jMenu3.add(jMenuItem7);

                jMenuBar1.add(jMenu3);

                jMenu4.setText("Utilitários");

                jMenuItem8.setText("Calculadora");
                jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItem8ActionPerformed(evt);
                        }
                });
                jMenu4.add(jMenuItem8);

                jMenuItem9.setText("Backup");
                jMenu4.add(jMenuItem9);

                jMenuBar1.add(jMenu4);

                setJMenuBar(jMenuBar1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(lblData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHora)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblData)
                                        .addComponent(lblHora)))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
                // TODO add your handling code here:
                
        }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente sair?","Sair",JOptionPane.YES_NO_OPTION)==0)
            System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

        private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
                // TODO add your handling code here:
		FrmCadUser caduser = new FrmCadUser();
		caduser.setVisible(true);
		
        }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    class Hora extends TimerTask{
        public void run(){
           hora = calendario.getTime();
           lblHora.setText(sdf.format(hora));
        }
    }
	/**
	 * @param args the command line arguments
	 */
	

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAnexo;
        private javax.swing.JButton btnCancelar;
        private javax.swing.JButton btnDinheiro;
        private javax.swing.JButton btnDisco;
        private javax.swing.JButton btnPrinter;
        private javax.swing.JButton btnUsers;
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenu jMenu2;
        private javax.swing.JMenu jMenu3;
        private javax.swing.JMenu jMenu4;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JMenuItem jMenuItem1;
        private javax.swing.JMenuItem jMenuItem2;
        private javax.swing.JMenuItem jMenuItem3;
        private javax.swing.JMenuItem jMenuItem5;
        private javax.swing.JMenuItem jMenuItem6;
        private javax.swing.JMenuItem jMenuItem7;
        private javax.swing.JMenuItem jMenuItem8;
        private javax.swing.JMenuItem jMenuItem9;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JToolBar jToolBar1;
        private javax.swing.JLabel lblData;
        private javax.swing.JLabel lblHora;
        private javax.swing.JMenuItem menuSair;
        // End of variables declaration//GEN-END:variables
}
